import React, { useState } from 'react';
import { TestPaper, ExerciseQuestion, GradeLevel, SubjectCategory } from '../types/curriculum';
import { SAMPLE_TEST_PAPERS } from '../data/testBank';
import confetti from 'canvas-confetti';
import { 
  FileText, 
  Clock, 
  CheckCircle2, 
  XCircle, 
  RotateCcw, 
  Award, 
  Sparkles, 
  Loader2, 
  PlusCircle, 
  Check,
  Zap
} from 'lucide-react';

interface TestBankViewProps {
  grade: GradeLevel;
  onSaveTestScore: (testId: string, score: number, total: number, subject: SubjectCategory) => void;
}

export const TestBankView: React.FC<TestBankViewProps> = ({
  grade,
  onSaveTestScore
}) => {
  const [activePaper, setActivePaper] = useState<TestPaper>(SAMPLE_TEST_PAPERS[0]);

  // Test session state
  const [testSessionState, setTestSessionState] = useState<'browse' | 'testing' | 'results'>('browse');
  const [selectedAnswers, setSelectedAnswers] = useState<Record<string, number>>({});
  const [timeLeftSeconds, setTimeLeftSeconds] = useState(activePaper.durationMinutes * 60);
  const [finalScore, setFinalScore] = useState(0);

  // Dynamic AI Question Generator State
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatorSubject, setGeneratorSubject] = useState<SubjectCategory>('Mathematics');
  const [aiGeneratedPaper, setAiGeneratedPaper] = useState<TestPaper | null>(null);

  const startTest = (paper: TestPaper) => {
    setActivePaper(paper);
    setSelectedAnswers({});
    setTimeLeftSeconds(paper.durationMinutes * 60);
    setTestSessionState('testing');
  };

  const handleSelectOption = (questionId: string, optionIndex: number) => {
    setSelectedAnswers(prev => ({ ...prev, [questionId]: optionIndex }));
  };

  const handleSubmitPaper = () => {
    let score = 0;
    activePaper.questions.forEach(q => {
      if (selectedAnswers[q.id] === q.correctAnswerIndex) {
        score++;
      }
    });

    setFinalScore(score);
    setTestSessionState('results');

    // Save score
    onSaveTestScore(activePaper.id, score, activePaper.questions.length, activePaper.subject);

    // Confetti if score >= 75%
    if ((score / activePaper.questions.length) >= 0.75) {
      confetti({
        particleCount: 120,
        spread: 80,
        origin: { y: 0.6 }
      });
    }
  };

  const handleGenerateAiPractice = async () => {
    setIsGenerating(true);
    try {
      const res = await fetch('/api/practice/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          grade,
          subject: generatorSubject,
          topic: 'General ZIMSEC Revision',
          count: 5
        })
      });

      const data = await res.json();
      if (res.ok && data.success && data.questions?.length > 0) {
        const customPaper: TestPaper = {
          id: `ai-gen-${Date.now()}`,
          title: `AI Generated ${grade} ${generatorSubject} Revision Paper`,
          type: 'ZIMSEC Mock Paper 1 (MCQ)',
          grade,
          subject: generatorSubject,
          durationMinutes: 20,
          totalQuestions: data.questions.length,
          questions: data.questions.map((q: any, i: number) => ({
            id: `aiq-${i}`,
            question: q.question,
            options: q.options,
            correctAnswerIndex: q.correctIndex ?? 0,
            explanation: q.explanation || 'Solution generated by AI Tutor.'
          }))
        };

        setAiGeneratedPaper(customPaper);
        startTest(customPaper);
      }
    } catch (err) {
      console.error("AI question generation error:", err);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-indigo-950 via-slate-900 to-slate-900 border border-indigo-800/60 rounded-2xl p-5 sm:p-6 shadow-xl relative overflow-hidden">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <div className="flex items-center space-x-2 text-xs text-indigo-400 font-semibold uppercase tracking-wider mb-1">
              <span>ZIMSEC Primary Exam Simulator & Test Bank</span>
              <span>•</span>
              <span>{grade}</span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
              Test Bank & Exam Practice
            </h2>
            <p className="text-sm text-slate-300 max-w-3xl mt-1 leading-relaxed">
              Grade 7 ZIMSEC style mock papers, mid-term progress checks, and AI-generated practice papers with step-by-step worked solutions!
            </p>
          </div>

          {/* AI Paper Generator trigger */}
          <div className="flex flex-col sm:flex-row items-center gap-2">
            <select
              value={generatorSubject}
              onChange={(e) => setGeneratorSubject(e.target.value as SubjectCategory)}
              className="bg-slate-950 border border-slate-800 text-xs text-slate-200 px-3 py-2 rounded-xl"
            >
              <option value="Mathematics">Maths Revision</option>
              <option value="English Language">English Paper</option>
              <option value="Science & Technology">Science & Tech</option>
              <option value="Heritage & Social Studies">Heritage Studies</option>
              <option value="Agriculture & Food Tech">Agriculture</option>
            </select>

            <button
              onClick={handleGenerateAiPractice}
              disabled={isGenerating}
              className="bg-indigo-600 hover:bg-indigo-500 text-white font-bold px-4 py-2 rounded-xl text-xs flex items-center space-x-2 transition cursor-pointer shadow-lg shadow-indigo-950"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Generating AI Paper...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-amber-300" />
                  <span>Generate New AI Test</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* MODE 1: BROWSE TEST PAPERS */}
      {testSessionState === 'browse' && (
        <div className="space-y-4">
          <h3 className="text-lg font-bold text-slate-100 flex items-center justify-between">
            <span>Available ZIMSEC & Mid-Term Test Papers</span>
            <span className="text-xs text-indigo-400 font-medium">
              {SAMPLE_TEST_PAPERS.length} Papers Ready
            </span>
          </h3>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {SAMPLE_TEST_PAPERS.map((paper) => (
              <div 
                key={paper.id}
                className="bg-slate-900 border border-slate-800 rounded-2xl p-5 hover:border-indigo-600/60 transition shadow-lg flex flex-col justify-between space-y-4"
              >
                <div>
                  <div className="flex items-center justify-between mb-2">
                    <span className="bg-indigo-950 text-indigo-400 border border-indigo-800 text-[10px] font-bold px-2.5 py-0.5 rounded-full">
                      {paper.type}
                    </span>
                    <span className="text-xs text-slate-400 font-medium">
                      {paper.grade}
                    </span>
                  </div>

                  <h4 className="font-bold text-base text-slate-100 leading-snug">
                    {paper.title}
                  </h4>

                  <div className="flex items-center space-x-3 text-xs text-slate-400 mt-2">
                    <span className="flex items-center gap-1">
                      <Clock className="w-3.5 h-3.5 text-indigo-400" />
                      {paper.durationMinutes} mins
                    </span>
                    <span>•</span>
                    <span>{paper.totalQuestions} Questions</span>
                  </div>
                </div>

                <button
                  onClick={() => startTest(paper)}
                  className="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-bold py-2.5 px-4 rounded-xl text-xs flex items-center justify-center space-x-2 transition cursor-pointer shadow-md shadow-indigo-950"
                >
                  <Zap className="w-4 h-4 fill-white" />
                  <span>Start Timed Test Paper</span>
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* MODE 2: ACTIVE TIMED TEST */}
      {testSessionState === 'testing' && (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 sm:p-6 shadow-2xl space-y-6">
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4">
            <div>
              <span className="text-xs font-bold text-indigo-400 uppercase tracking-wider block">
                {activePaper.subject} • {activePaper.type}
              </span>
              <h3 className="text-xl font-bold text-slate-100">
                {activePaper.title}
              </h3>
            </div>

            <div className="bg-slate-950 border border-indigo-800/80 px-4 py-2 rounded-xl text-indigo-300 font-mono text-sm flex items-center gap-2">
              <Clock className="w-4 h-4 text-indigo-400" />
              <span>{activePaper.durationMinutes} Mins Allocated</span>
            </div>
          </div>

          <div className="space-y-6">
            {activePaper.questions.map((q, idx) => {
              const selectedOpt = selectedAnswers[q.id];

              return (
                <div key={q.id} className="bg-slate-950 border border-slate-800 rounded-2xl p-5 space-y-3">
                  <h4 className="font-bold text-base text-slate-100">
                    <span className="text-indigo-400 font-black mr-2">Q{idx + 1}.</span>
                    {q.question}
                  </h4>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                    {q.options.map((optText, oIdx) => {
                      const isSelected = selectedOpt === oIdx;
                      return (
                        <button
                          key={oIdx}
                          onClick={() => handleSelectOption(q.id, oIdx)}
                          className={`p-3.5 rounded-xl border text-xs sm:text-sm text-left transition cursor-pointer ${
                            isSelected
                              ? 'bg-indigo-600/30 border-indigo-500 text-white font-bold ring-2 ring-indigo-500/50'
                              : 'bg-slate-900 border-slate-800 text-slate-300 hover:bg-slate-800'
                          }`}
                        >
                          <span>{optText}</span>
                        </button>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>

          <div className="flex justify-between items-center pt-4 border-t border-slate-800">
            <button
              onClick={() => setTestSessionState('browse')}
              className="text-xs text-slate-400 hover:text-slate-200 underline cursor-pointer"
            >
              Cancel & Back to Test Bank
            </button>

            <button
              onClick={handleSubmitPaper}
              disabled={Object.keys(selectedAnswers).length < activePaper.questions.length}
              className={`px-6 py-3 rounded-xl font-bold text-xs flex items-center space-x-2 transition cursor-pointer shadow-lg ${
                Object.keys(selectedAnswers).length === activePaper.questions.length
                  ? 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-emerald-950'
                  : 'bg-slate-800 text-slate-500 cursor-not-allowed'
              }`}
            >
              <span>Submit & Grade ZIMSEC Paper</span>
              <Check className="w-4 h-4" />
            </button>
          </div>
        </div>
      )}

      {/* MODE 3: TEST RESULTS & SOLUTION WALKTHROUGH */}
      {testSessionState === 'results' && (
        <div className="space-y-6">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 text-center space-y-4 shadow-xl">
            <div className="w-16 h-16 rounded-full bg-emerald-950 border-2 border-emerald-500 mx-auto flex items-center justify-center">
              <Award className="w-8 h-8 text-emerald-400" />
            </div>

            <h3 className="text-2xl font-extrabold text-white">
              Paper Graded: {finalScore} / {activePaper.questions.length}
            </h3>

            <div className="flex justify-center space-x-3">
              <button
                onClick={() => setTestSessionState('browse')}
                className="bg-slate-800 hover:bg-slate-700 text-slate-200 px-5 py-2 rounded-xl text-xs font-bold cursor-pointer transition"
              >
                Back to Test Bank
              </button>

              <button
                onClick={() => startTest(activePaper)}
                className="bg-indigo-600 hover:bg-indigo-500 text-white px-5 py-2 rounded-xl text-xs font-bold cursor-pointer transition shadow-md"
              >
                Retake Paper
              </button>
            </div>
          </div>

          {/* Solution Walkthrough */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 sm:p-6 space-y-4 shadow-xl">
            <h4 className="text-lg font-bold text-slate-100 border-b border-slate-800 pb-2">
              Worked Solutions & Explanations:
            </h4>

            <div className="space-y-4">
              {activePaper.questions.map((q, idx) => {
                const userChoice = selectedAnswers[q.id];
                const isCorrect = userChoice === q.correctAnswerIndex;

                return (
                  <div key={q.id} className="bg-slate-950 border border-slate-800 p-4 rounded-xl space-y-2">
                    <div className="flex items-start justify-between">
                      <span className="font-bold text-sm text-slate-100">
                        Q{idx + 1}. {q.question}
                      </span>
                      {isCorrect ? (
                        <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
                      ) : (
                        <XCircle className="w-5 h-5 text-rose-400 shrink-0" />
                      )}
                    </div>

                    <div className="text-xs text-slate-300">
                      <span className="font-bold text-slate-400">Correct Answer: </span>
                      <span className="text-emerald-400 font-bold">{q.options[q.correctAnswerIndex]}</span>
                    </div>

                    <div className="bg-slate-900 p-3 rounded-lg text-xs text-slate-300 border border-slate-800">
                      <span className="font-bold text-amber-400">Step-by-Step Explanation: </span>
                      {q.explanation}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
